channels:
- conda-forge
dependencies:
- python=3.10.5
- pip<=22.0.4
- pip:
  - mlflow==2.9.2
  - cloudpickle==3.0.0
  - numpy==1.23.5
  - packaging==21.3
  - psutil==5.9.1
  - pyyaml==6.0
  - scikit-learn==1.1.2
  - scipy==1.9.1
name: mlflow-env
